javascripts:
  common:
    - public/javascripts/jqueryslidemenu.js
    - public/javascripts/jquery.autocomplete.js
    - public/javascripts/jquery.livequery.js
    - public/javascripts/jquery.date_input.js
    - public/javascripts/jquery.date_input.zh_CN.js
    - public/javascripts/validanguage.js
    - public/javascripts/tooltip.js
    - public/javascripts/application.js
    - public/javascripts/upload.js
